#!name=糖心Vlog
#!desc=糖心Vlog 解锁点播去除广告
#!icon=https://txscript.pages.dev/tx/icon.png

[Script]
糖心Vlog = type=http-request, pattern=^https?:\/\/((?:[a-z]+\.)?txh\d+\.com)\/(h5\/(?:user\/info|system\/info|movie\/(?:detail|block|search))), requires-body=true, script-path=https://
txscript.pages.dev/tx/qx.js, timeout=15, enable=true

[MITM]
hostname = %APPEND% *.txh066.com, *.txh067.com, *.txh068.com, *.txh069.com, *.txh087.com, txh066.com, txh067.com, txh068.com, txh069.com, txh087.com